<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Receipt Verification - Alchy Enterprises</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        body {
            background: linear-gradient(135deg, #0f172a 0%, #1e293b 100%);
            min-height: 100vh;
        }
    </style>
</head>
<body class="antialiased">
    <div class="min-h-screen flex items-center justify-center p-4">
        <div class="max-w-2xl w-full">
            <!-- Logo -->
            <div class="text-center mb-8">
                <h1 class="text-3xl font-bold text-white">Alchy Enterprises Inc.</h1>
                <p class="text-gray-400 mt-1">Receipt Verification System</p>
            </div>

            <!-- Verification Result Card -->
            <div class="bg-[#101828] rounded-3xl shadow-2xl border border-[#1B2537] overflow-hidden">
                @if($status === 'valid')
                    <!-- Valid Receipt -->
                    <div class="bg-gradient-to-r from-emerald-500 to-green-600 p-6 text-center">
                        <div class="inline-flex items-center justify-center w-20 h-20 bg-white/20 rounded-full mb-4">
                            <svg class="w-12 h-12 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 13l4 4L19 7"></path>
                            </svg>
                        </div>
                        <h2 class="text-3xl font-bold text-white mb-2">Verified Authentic</h2>
                        <p class="text-emerald-50">This receipt is genuine and has been verified successfully.</p>
                    </div>

                    <div class="p-8">
                        <!-- Project Information -->
                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                            <div class="bg-[#0d1829] rounded-2xl p-5 border border-emerald-500/20">
                                <p class="text-xs uppercase tracking-wide text-gray-500 mb-2">Project Name</p>
                                <p class="text-lg font-semibold text-white">{{ $verification->project->name }}</p>
                            </div>
                            <div class="bg-[#0d1829] rounded-2xl p-5 border border-emerald-500/20">
                                <p class="text-xs uppercase tracking-wide text-gray-500 mb-2">Reference Code</p>
                                <p class="text-lg font-semibold text-white">{{ $verification->project->reference_code ?: 'N/A' }}</p>
                            </div>
                        </div>

                        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                            <div class="bg-[#0d1829] rounded-2xl p-5 border border-emerald-500/20">
                                <p class="text-xs uppercase tracking-wide text-gray-500 mb-2">Client</p>
                                <p class="text-base font-semibold text-white">{{ $verification->project->client->name }}</p>
                                <p class="text-sm text-gray-400 mt-1">{{ $verification->project->client->branch }}</p>
                            </div>
                            <div class="bg-[#0d1829] rounded-2xl p-5 border border-emerald-500/20">
                                <p class="text-xs uppercase tracking-wide text-gray-500 mb-2">Total Expenses</p>
                                <p class="text-lg font-semibold text-emerald-400">₱{{ number_format($verification->receipt_data['total_expenses'] ?? 0, 2) }}</p>
                                <p class="text-sm text-gray-400 mt-1">{{ $verification->receipt_data['expense_count'] ?? 0 }} items</p>
                            </div>
                        </div>

                        <!-- Verification Details -->
                        <div class="bg-emerald-500/10 rounded-2xl p-5 border border-emerald-500/30 mb-6">
                            <h3 class="text-sm font-bold text-emerald-400 mb-4 uppercase tracking-wide">Verification Details</h3>
                            <div class="space-y-3">
                                <div class="flex justify-between items-center">
                                    <span class="text-sm text-gray-400">Receipt Generated</span>
                                    <span class="text-sm font-semibold text-white">{{ $verification->generated_at->format('M d, Y h:i A') }}</span>
                                </div>
                                <div class="flex justify-between items-center">
                                    <span class="text-sm text-gray-400">Generated By</span>
                                    <span class="text-sm font-semibold text-white">{{ $verification->generated_by }}</span>
                                </div>
                                <div class="flex justify-between items-center">
                                    <span class="text-sm text-gray-400">Times Verified</span>
                                    <span class="text-sm font-semibold text-emerald-400">{{ $verification->verified_count }}x</span>
                                </div>
                                <div class="flex justify-between items-center">
                                    <span class="text-sm text-gray-400">Last Verified</span>
                                    <span class="text-sm font-semibold text-white">{{ $verification->last_verified_at->format('M d, Y h:i A') }}</span>
                                </div>
                            </div>
                        </div>

                        <!-- Hash Display -->
                        <div class="bg-[#0d1829] rounded-2xl p-5 border border-[#1B2537]">
                            <p class="text-xs uppercase tracking-wide text-gray-500 mb-2">Verification Hash</p>
                            <p class="text-xs font-mono text-gray-400 break-all">{{ $verification->verification_hash }}</p>
                        </div>
                    </div>
                @else
                    <!-- Invalid Receipt -->
                    <div class="bg-gradient-to-r from-red-500 to-rose-600 p-6 text-center">
                        <div class="inline-flex items-center justify-center w-20 h-20 bg-white/20 rounded-full mb-4">
                            <svg class="w-12 h-12 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M6 18L18 6M6 6l12 12"></path>
                            </svg>
                        </div>
                        <h2 class="text-3xl font-bold text-white mb-2">⚠️ Verification Failed</h2>
                        <p class="text-red-50">This receipt could not be verified in our system.</p>
                    </div>

                    <div class="p-8">
                        <div class="bg-red-500/10 rounded-2xl p-6 border border-red-500/30 mb-6">
                            <h3 class="text-lg font-bold text-red-400 mb-3">❌ Invalid Verification Code</h3>
                            <p class="text-gray-300 mb-4">The verification code you provided does not match any records in our database.</p>
                            
                            <div class="bg-[#0d1829] rounded-xl p-4 border border-red-500/20">
                                <p class="text-sm font-semibold text-red-300 mb-2">Possible Reasons:</p>
                                <ul class="text-sm text-gray-400 space-y-1 list-disc list-inside">
                                    <li>The receipt has been modified or tampered with</li>
                                    <li>The QR code was damaged or incorrectly scanned</li>
                                    <li>This is not an official Alchy receipt</li>
                                    <li>The verification link is incorrect or incomplete</li>
                                </ul>
                            </div>
                        </div>

                        <div class="bg-amber-500/10 rounded-2xl p-6 border border-amber-500/30">
                            <h3 class="text-lg font-bold text-amber-400 mb-3">⚠️ Security Alert</h3>
                            <p class="text-gray-300">If you believe this is an authentic Alchy receipt, please contact our office immediately to report a potential security issue.</p>
                        </div>
                    </div>
                @endif

                <!-- Action Buttons -->
                <div class="px-8 pb-8 pt-4 border-t border-[#1B2537]">
                    <div class="flex flex-col sm:flex-row gap-3">
                        <a href="{{ route('receipt-scanner') }}" class="flex-1 inline-flex items-center justify-center gap-2 px-6 py-3 bg-primary-500 hover:bg-primary-600 text-white font-semibold rounded-xl transition-colors">
                            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z"></path>
                            </svg>
                            Scan Another Receipt
                        </a>
                        @auth
                            <a href="{{ route('dashboard') }}" class="flex-1 inline-flex items-center justify-center gap-2 px-6 py-3 bg-gray-700 hover:bg-gray-600 text-white font-semibold rounded-xl transition-colors">
                                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path>
                                </svg>
                                Back to Dashboard
                            </a>
                        @else
                            <a href="/" class="flex-1 inline-flex items-center justify-center gap-2 px-6 py-3 bg-gray-700 hover:bg-gray-600 text-white font-semibold rounded-xl transition-colors">
                                <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path>
                                </svg>
                                Back to Home
                            </a>
                        @endauth
                    </div>
                </div>
            </div>

            <!-- Footer -->
            <div class="text-center mt-8 text-gray-400 text-sm">
                <p>© {{ date('Y') }} Alchy Enterprises Inc. • Smart Inventory System</p>
                <p class="mt-1">Secure Receipt Verification with Blockchain-Inspired Technology</p>
            </div>
        </div>
    </div>
</body>
</html>
